"use client";
import { ArrowRight, CheckCircle2, ShieldCheck } from "lucide-react";
import { type Persona, type PersonaId } from "../data/personas";
import { NewChatLanding } from "./NewChatLanding";

const detail: Record<Exclude<PersonaId,"radu">, { checked:string; result:string; evidence:string[]; next:string }> = {
  amelie:{checked:"I will check curriculum fit, trainer availability, room capacity and Claire’s 30 September deadline before proposing a session.",result:"One viable classroom session is ready: Friday 18 September in Paris with Victor Laurent and 16 seats. Publishing creates Radu’s registration package only.",evidence:["Curriculum and planning rules", "Victor Laurent availability", "Room capacity and lead time"],next:"Approve the session plan for Learning Operations"},
  claire:{checked:"I found the mandatory learning path. Confirm the 12 people and whether Victor is a preference or a requirement before I send the request for planning.",result:"The proposed 18 September session works for 10 people. Priya has a calendar conflict and Thomas starts after the session.",evidence:["Curriculum requirement", "Paris delivery preference", "12-person cohort"],next:"Review 2 business decisions"},
  elena:{checked:"I completed the weekly INV-04 invitation match against confirmed registrations for the New Manager Foundations cohort.",result:"INV-04 found one confirmed registration without a matching current Outlook invitation. Contained remediation is ready for your approval.",evidence:["Control catalogue INV-04", "Source timestamps retained", "Participant impact: 1 learner"],next:"Approve remediation and re-check"}
};
export function PersonaFlow({persona, step, setStep}:{persona:Persona;step:number;setStep:(value:number)=>void}){ const d=detail[persona.id as Exclude<PersonaId,"radu">]; if(step===1) return <NewChatLanding persona={persona} onStartChat={()=>setStep(2)} onStartDemo={()=>setStep(2)}/>;
  return <div className="mx-auto max-w-5xl"><h1 className="text-3xl font-bold tracking-tight md:text-4xl">{persona.flowTitle}</h1><div className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-[var(--line)] bg-white p-5 shadow-[0_8px_28px_rgba(20,20,20,.035)]"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-zinc-900 text-white"><ShieldCheck size={18}/></span><div><p className="font-bold">{step===2?d.checked:d.result}</p><p className="mt-2 text-sm leading-6 text-zinc-600">Rule applied and evidence retained. No background action is complete until a named person approves it.</p></div></div>{step===3&&<div className="mt-5 rounded-xl border-l-4 border-[var(--sg-red)] bg-zinc-50 p-4"><p className="font-bold">Needs decision</p><p className="mt-1 text-sm text-zinc-600">{d.next}. You can review the recommendation, choose an alternative, or keep the draft unchanged.</p></div>}<button onClick={()=>setStep(step===2?3:2)} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[var(--sg-red)] px-4 py-2.5 text-sm font-bold text-white">{step===2?persona.primaryAction:"Back to brief"}<ArrowRight size={16}/></button></section><section className="rounded-2xl border border-[var(--line)] bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Systems checked</p><div className="mt-4 space-y-3">{d.evidence.map(x=><div key={x} className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 size={17} className="text-emerald-600"/>{x}</div>)}</div><div className="mt-6 border-t border-zinc-100 pt-4"><p className="text-3xl font-bold">{persona.stats[0].value}</p><p className="text-sm text-zinc-500">{persona.stats[0].label}</p></div></section></div></div> }
