import { CalendarPlus, ClipboardCheck, FileSearch, Users } from "lucide-react";
import { type PersonaId } from "../data/personas";
const actions: Record<PersonaId,{label:string;description:string;icon:typeof CalendarPlus}[]> = {
  radu:[{label:"Prepare registrations",description:"Check a cohort before approval",icon:Users},{label:"Handle a cancellation",description:"Find a replacement or leave a seat open",icon:CalendarPlus},{label:"Review an exception",description:"See rule evidence and recommendations",icon:FileSearch}],
  amelie:[{label:"Plan a programme",description:"Build a viable classroom schedule",icon:CalendarPlus},{label:"Review capacity",description:"Check rooms, trainers and seats",icon:ClipboardCheck},{label:"Resolve a planning conflict",description:"Choose a compliant alternative",icon:FileSearch}],
  claire:[{label:"Train a new cohort",description:"Request mandatory learning for your team",icon:Users},{label:"Check team learning",description:"See open needs and confirmations",icon:ClipboardCheck},{label:"Request a change",description:"Update a learning request",icon:CalendarPlus}],
  elena:[{label:"Review control exceptions",description:"Focus on decision-required items",icon:FileSearch},{label:"Check invitation coverage",description:"Find participant-impact issues",icon:ClipboardCheck},{label:"Assign remediation",description:"Set owner, due date and proof",icon:Users}],
};
export function QuickActions({persona,onSelect}:{persona:PersonaId;onSelect:(label:string)=>void}){return <div className="mt-5 grid gap-2 sm:grid-cols-3">{actions[persona].map(({label,description,icon:Icon})=><button key={label} onClick={()=>onSelect(label)} className="group rounded-xl border border-[var(--line)] bg-white p-4 text-left transition hover:border-zinc-300 hover:shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-lg bg-zinc-100 text-zinc-700 group-hover:bg-red-50 group-hover:text-[var(--sg-red)]"><Icon size={17}/></span><p className="mt-4 text-sm font-bold">{label}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{description}</p></button>)}</div>}
