"use client";
import { useMemo, useState } from "react";
import { Bell, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Ellipsis, Folder, Globe2, LogOut, MessageSquare, PanelLeftClose, Plus, Search, Settings2, UserRound } from "lucide-react";
import { type NavKey, type Persona, type PersonaId, navigationFor, personas } from "../data/personas";

type Conversation={id:number;title:string;when:string;project?:string}; type Project={id:number;name:string;open:boolean};
type Props = { section:NavKey; persona:Persona; collapsed:boolean; menuOpen:boolean; onToggle:()=>void; onSection:(s:NavKey)=>void; onMenu:()=>void; onPersona:(id:PersonaId)=>void };
const seed:Record<PersonaId,Conversation[]>={radu:[{id:1,title:"New Manager Foundations · Paris",when:"Today",project:"Manager onboarding"},{id:2,title:"Replace a cancelled attendee",when:"2 days ago"},{id:3,title:"September invitation follow-up",when:"5 days ago"}],amelie:[{id:1,title:"Paris new-manager programme",when:"Today",project:"Q4 learning plan"},{id:2,title:"October room availability",when:"3 days ago"},{id:3,title:"Trainer plan · Q4",when:"8 days ago"}],claire:[{id:1,title:"New manager learning request",when:"Today",project:"My team"},{id:2,title:"Team mandatory learning",when:"6 days ago"},{id:3,title:"Request REF-248",when:"12 days ago"}],elena:[{id:1,title:"Weekly invitation controls",when:"Today",project:"Weekly controls"},{id:2,title:"INV-04 remediation review",when:"4 days ago"},{id:3,title:"August control pack",when:"9 days ago"}]};
const seedProjects:Record<PersonaId,string[]>={radu:["Manager onboarding"],amelie:["Q4 learning plan"],claire:["My team"],elena:["Weekly controls"]};

export function SideNav({section,persona,collapsed,menuOpen,onToggle,onSection,onMenu,onPersona}:Props){
  const [query,setQuery]=useState(""); const [searchOpen,setSearchOpen]=useState(false); const [recentOpen,setRecentOpen]=useState(true); const [projects,setProjects]=useState<Project[]>(()=>seedProjects[persona.id].map((name,id)=>({id,name,open:true}))); const [conversations,setConversations]=useState<Conversation[]>(()=>seed[persona.id]); const [activeMenu,setActiveMenu]=useState<number|null>(null); const items=navigationFor(persona.id).filter(i=>i.key!=="assistant");
  const visible=useMemo(()=>conversations.filter(c=>c.title.toLowerCase().includes(query.toLowerCase())),[conversations,query]);
  const resetForPersona=(id:PersonaId)=>{setConversations(seed[id]);setProjects(seedProjects[id].map((name,index)=>({id:index,name,open:true})));setQuery("");onPersona(id)};
  const addProject=()=>{const name=window.prompt("Project name");if(name?.trim())setProjects(v=>[...v,{id:Date.now(),name:name.trim(),open:true}])};
  const rename=(id:number)=>{const old=conversations.find(c=>c.id===id);const title=window.prompt("Conversation name",old?.title);if(title?.trim())setConversations(v=>v.map(c=>c.id===id?{...c,title:title.trim()}:c));setActiveMenu(null)};
  const move=(id:number)=>{const names=projects.map(p=>p.name).join(", ");const project=window.prompt(`Move to project (${names})`,projects[0]?.name);if(project?.trim())setConversations(v=>v.map(c=>c.id===id?{...c,project:project.trim()}:c));setActiveMenu(null)};
  const remove=(id:number)=>{setConversations(v=>v.filter(c=>c.id!==id));setActiveMenu(null)};
  const conversationRow=(c:Conversation, nested=false)=><div key={c.id} className="group relative"><button onClick={()=>onSection("assistant")} className={`flex w-full items-start gap-2 rounded-lg px-2 py-2 text-left hover:bg-white/8 ${nested?"pl-8":""}`}><MessageSquare className="mt-0.5 shrink-0 text-zinc-500" size={15}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium text-zinc-300">{c.title}</span><span className="mt-0.5 block text-[11px] text-zinc-500">{c.when}</span></span></button><button aria-label={`Conversation options for ${c.title}`} onClick={()=>setActiveMenu(activeMenu===c.id?null:c.id)} className="absolute right-1 top-2 hidden rounded p-1 text-zinc-400 hover:bg-white/10 group-hover:block"><Ellipsis size={16}/></button>{activeMenu===c.id&&<div className="absolute right-0 top-8 z-[80] w-36 rounded-lg border border-zinc-700 bg-zinc-900 p-1 shadow-2xl"><button onClick={()=>rename(c.id)} className="w-full rounded px-2 py-2 text-left text-xs hover:bg-white/10">Rename</button><button onClick={()=>move(c.id)} className="w-full rounded px-2 py-2 text-left text-xs hover:bg-white/10">Move to project</button><button onClick={()=>remove(c.id)} className="w-full rounded px-2 py-2 text-left text-xs text-red-300 hover:bg-red-500/15">Delete</button></div>}</div>;
  return <aside className={`${collapsed?"w-[76px]":"w-[300px]"} flex h-full shrink-0 flex-col bg-[#202124] p-4 text-white transition-all duration-200`}>
    <div className={`mb-5 flex items-start ${collapsed?"justify-center":"justify-between gap-2"} overflow-visible`}><button onClick={onToggle} aria-label={collapsed?"Expand navigation":"Collapse navigation"} className="group relative rounded-lg p-2 hover:bg-white/10">{collapsed?<img src="/brand/SocGen_logo_only.svg" alt="Société Générale" className="h-8 w-8"/>:<><img src="/logo_white.svg" alt="Société Générale" className="h-auto w-[160px]"/><p className="mt-2 text-xs font-bold tracking-[.17em] text-zinc-300">HR ASSISTANT</p></>}{collapsed&&<span className="tooltip">Expand navigation</span>}</button>{!collapsed&&<div className="flex"><button aria-label="Search conversations" onClick={()=>setSearchOpen(true)} className="rounded p-2 text-zinc-300 hover:bg-white/10"><Search size={20}/></button><button aria-label="Collapse navigation" onClick={onToggle} className="rounded p-2 text-zinc-300 hover:bg-white/10"><PanelLeftClose size={19}/></button></div>}</div>
    <button onClick={()=>onSection("assistant")} className={`group relative flex w-full items-center gap-3 rounded-xl border px-4 py-3.5 text-left text-base font-bold transition ${section==="assistant"?"border-white/20 bg-white/10 text-white":"border-white/20 text-white hover:bg-white/10"}`}><Plus className="text-[#ff8b98]" size={22}/>{!collapsed&&<span>New chat</span>}{collapsed&&<span className="tooltip">New chat</span>}</button>
    <nav className="mt-5 space-y-1">{items.map(({key,label,icon:Icon})=><button key={key} onClick={()=>onSection(key)} className={`group relative flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-semibold transition ${section===key?"bg-white/12 text-white":"text-zinc-400 hover:bg-white/8 hover:text-white"}`}><Icon size={18}/>{!collapsed&&<span>{label}</span>}{collapsed&&<span className="tooltip">{label}</span>}</button>)}</nav>
    {!collapsed&&<div className="scrollbar mt-5 min-h-0 flex-1 overflow-y-auto pr-1"><div className="flex items-center justify-between px-2 py-2"><button onClick={()=>setProjects(v=>v.map(p=>({...p,open:!p.open})))} className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-zinc-500 hover:text-zinc-300"><ChevronDown size={15}/> Projects</button><button aria-label="Create project" onClick={addProject} className="rounded p-1 text-zinc-400 hover:bg-white/10"><Plus size={17}/></button></div>{projects.map(p=><div key={p.id} className="mb-1"><button onClick={()=>setProjects(v=>v.map(x=>x.id===p.id?{...x,open:!x}:x))} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm font-semibold text-zinc-200 hover:bg-white/10"><Folder size={18}/><span className="truncate flex-1">{p.name}</span><ChevronRight size={15} className={p.open?"rotate-90":""}/></button>{p.open&&conversations.filter(c=>c.project===p.name).map(c=>conversationRow(c,true))}</div>)}<div className="mt-5"><button onClick={()=>setRecentOpen(v=>!v)} aria-expanded={recentOpen} className="flex w-full items-center gap-2 px-2 py-2 text-xs font-bold uppercase tracking-[.14em] text-zinc-500 hover:text-zinc-300"><ChevronDown size={15} className={recentOpen?"":"-rotate-90"}/> Recent</button>{recentOpen&&visible.filter(c=>!c.project).map(c=>conversationRow(c))}</div></div>}
    <div className="relative mt-auto border-t border-white/15 pt-4"><button onClick={onMenu} aria-expanded={menuOpen} className="group flex w-full items-center gap-3 rounded-lg p-1 text-left hover:bg-white/10"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-zinc-600 text-xs font-bold">{persona.initials}</span>{!collapsed&&<div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{persona.name}</p><p className="truncate text-xs text-zinc-400">{persona.role}</p></div>}{!collapsed&&<Ellipsis size={18} className="text-zinc-300"/>}{collapsed&&<span className="tooltip">{persona.name} · Settings</span>}</button>{menuOpen&&<div className={`absolute bottom-14 z-[70] w-[290px] overflow-hidden rounded-2xl border border-zinc-200 bg-white text-zinc-900 shadow-2xl ${collapsed?"left-0":"left-0"}`}><div className="flex gap-3 p-5"><span className="grid h-12 w-12 place-items-center rounded-full bg-zinc-900 text-sm font-bold text-white">{persona.initials}</span><div><p className="font-bold">{persona.name}</p><p className="text-sm text-zinc-500">{persona.role}</p><p className="mt-1 text-sm text-zinc-400">{persona.name.toLowerCase().replace(" ",".")}@socgen.com</p></div></div><div className="border-t border-zinc-200 py-2"><button className="menu-item"><Bell size={20}/>Notifications <span className="ml-auto h-2 w-2 rounded-full bg-[var(--sg-red)]"/></button><button className="menu-item"><Globe2 size={20}/>Language <span className="ml-auto text-zinc-500">English ›</span></button><button className="menu-item"><CircleHelp size={20}/>Help</button></div><div className="border-t border-zinc-200 p-2"><p className="px-3 py-2 text-xs font-bold uppercase tracking-wider text-zinc-400"><Settings2 className="mr-1 inline" size={13}/> Switch persona</p>{personas.map(p=><button key={p.id} onClick={()=>resetForPersona(p.id)} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left hover:bg-zinc-100"><span className="grid h-7 w-7 place-items-center rounded-full bg-zinc-200 text-[10px] font-bold">{p.initials}</span><span className="flex-1 text-sm font-medium">{p.name}</span>{p.id===persona.id&&<Check size={15} className="text-emerald-600"/>}</button>)}</div><div className="border-t border-zinc-200 p-2"><button className="menu-item text-[var(--sg-red)]"><LogOut size={20}/>Log out</button></div></div>}</div>
    {searchOpen&&<div role="dialog" aria-modal="true" aria-label="Search conversations" className="fixed inset-0 z-[100] grid place-items-start bg-black/45 px-4 pt-[14vh] backdrop-blur-sm"><div className="w-full max-w-xl overflow-hidden rounded-2xl bg-white text-zinc-900 shadow-2xl"><div className="flex items-center gap-3 border-b border-zinc-200 p-4"><Search size={20} className="text-zinc-500"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations and projects" className="min-w-0 flex-1 outline-none"/><button onClick={()=>setSearchOpen(false)} className="rounded border border-zinc-200 px-2 py-1 text-xs font-bold text-zinc-500">Esc</button></div><div className="max-h-80 overflow-y-auto p-2">{visible.map(c=><button key={c.id} onClick={()=>{onSection("assistant");setSearchOpen(false)}} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-zinc-100"><MessageSquare size={18} className="text-zinc-500"/><span className="flex-1"><span className="block text-sm font-semibold">{c.title}</span><span className="text-xs text-zinc-500">{c.project?`Project · ${c.project}`:c.when}</span></span></button>)}{visible.length===0&&<p className="p-4 text-sm text-zinc-500">No conversations found.</p>}</div></div></div>}
  </aside>
}
