"use client";
import { ChevronLeft, ChevronRight, Check, Settings2 } from "lucide-react";
import { type NavKey, type Persona, type PersonaId, navigationFor, personas } from "../data/personas";
type Props = { section:NavKey; persona:Persona; collapsed:boolean; menuOpen:boolean; onToggle:()=>void; onSection:(s:NavKey)=>void; onMenu:()=>void; onPersona:(id:PersonaId)=>void };
export function SideNav({section,persona,collapsed,menuOpen,onToggle,onSection,onMenu,onPersona}:Props){ const items=navigationFor(persona.id); return <aside className={`${collapsed?"w-[76px]":"w-[252px]"} flex h-full shrink-0 flex-col bg-[#202124] p-4 text-white transition-all duration-200`}>
  <div className={`mb-8 flex items-start ${collapsed?"justify-center":"justify-between gap-2"} overflow-visible`}><button onClick={onToggle} aria-label={collapsed?"Expand navigation":"Collapse navigation"} className="group relative rounded-lg p-2 hover:bg-white/10">{collapsed?<img src="/brand/SocGen_logo_only.svg" alt="Société Générale" className="h-8 w-8"/>:<img src="/logo_white.svg" alt="Société Générale" className="h-auto w-[148px]"/>}{collapsed&&<span className="pointer-events-none absolute left-12 top-2 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">Expand navigation</span>}</button>{!collapsed&&<button aria-label="Collapse navigation" onClick={onToggle} className="rounded p-2 text-zinc-300 hover:bg-white/10"><ChevronLeft size={19}/></button>}</div>
  {!collapsed&&<p className="-mt-5 mb-5 text-xs font-bold tracking-[.17em] text-zinc-300">HR ASSISTANT</p>}
  <nav className="space-y-2">{items.map(({key,label,icon:Icon})=><button key={key} onClick={()=>onSection(key)} className={`group relative flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold transition ${section===key?"bg-white/12 text-white":"text-zinc-400 hover:bg-white/8 hover:text-white"}`}><Icon size={19}/>{!collapsed&&<span>{label}</span>}{collapsed&&<span className="pointer-events-none absolute left-14 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">{label}</span>}</button>)}</nav>
  <div className="relative mt-auto border-t border-white/15 pt-4"><button onClick={onMenu} aria-expanded={menuOpen} className="group flex w-full min-w-[42px] items-center gap-3 rounded-lg p-1 text-left hover:bg-white/10"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-zinc-600 text-xs font-bold">{persona.initials}</span>{!collapsed&&<div className="min-w-0"><p className="truncate text-sm font-semibold">{persona.name}</p><p className="truncate text-xs text-zinc-400">{persona.role}</p></div>}{collapsed&&<span className="pointer-events-none absolute bottom-10 left-14 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">{persona.name} · Settings</span>}</button>{menuOpen&&<div className={`absolute bottom-14 z-[70] w-[280px] rounded-xl border border-zinc-700 bg-zinc-900 p-2 shadow-2xl ${collapsed?"left-0":"left-0"}`}><div className="flex items-center gap-2 px-3 py-2 text-xs font-bold uppercase tracking-wider text-zinc-400"><Settings2 size={14}/> Switch demo persona</div>{personas.map(p=><button key={p.id} onClick={()=>onPersona(p.id)} className="flex w-full items-center gap-3 rounded-lg p-3 text-left hover:bg-white/10"><span className="grid h-8 w-8 place-items-center rounded-full bg-zinc-700 text-xs font-bold">{p.initials}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{p.name}</span><span className="block truncate text-xs text-zinc-400">{p.role}</span></span>{p.id===persona.id&&<Check size={16} className="text-emerald-400"/>}</button>)}</div>}</div>
</aside> }
