"use client";
import { useState } from "react";
import { ChevronDown, ChevronLeft, Check, MessageSquare, Plus, Search, Settings2 } from "lucide-react";
import { type NavKey, type Persona, type PersonaId, navigationFor, personas } from "../data/personas";
type Props = { section:NavKey; persona:Persona; collapsed:boolean; menuOpen:boolean; onToggle:()=>void; onSection:(s:NavKey)=>void; onMenu:()=>void; onPersona:(id:PersonaId)=>void };
const recentByPersona: Record<PersonaId,{title:string;when:string}[]> = {radu:[{title:"New Manager Foundations · Paris",when:"Today"},{title:"Replace a cancelled attendee",when:"2 days ago"},{title:"September invitation follow-up",when:"5 days ago"}],amelie:[{title:"Paris new-manager programme",when:"Today"},{title:"October room availability",when:"3 days ago"},{title:"Trainer plan · Q4",when:"8 days ago"}],claire:[{title:"New manager learning request",when:"Today"},{title:"Team mandatory learning",when:"6 days ago"},{title:"Request REF-248",when:"12 days ago"}],elena:[{title:"Weekly invitation controls",when:"Today"},{title:"INV-04 remediation review",when:"4 days ago"},{title:"August control pack",when:"9 days ago"}]};
export function SideNav({section,persona,collapsed,menuOpen,onToggle,onSection,onMenu,onPersona}:Props){ const [recentOpen,setRecentOpen]=useState(true); const [query,setQuery]=useState(""); const items=navigationFor(persona.id).filter(i=>i.key!=="assistant"); const recents=recentByPersona[persona.id].filter(x=>x.title.toLowerCase().includes(query.toLowerCase())); return <aside className={`${collapsed?"w-[76px]":"w-[252px]"} flex h-full shrink-0 flex-col bg-[#202124] p-4 text-white transition-all duration-200`}>
  <div className={`mb-8 flex items-start ${collapsed?"justify-center":"justify-between gap-2"} overflow-visible`}><button onClick={onToggle} aria-label={collapsed?"Expand navigation":"Collapse navigation"} className="group relative rounded-lg p-2 hover:bg-white/10">{collapsed?<img src="/brand/SocGen_logo_only.svg" alt="Société Générale" className="h-8 w-8"/>:<img src="/logo_white.svg" alt="Société Générale" className="h-auto w-[148px]"/>}{collapsed&&<span className="pointer-events-none absolute left-12 top-2 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">Expand navigation</span>}</button>{!collapsed&&<button aria-label="Collapse navigation" onClick={onToggle} className="rounded p-2 text-zinc-300 hover:bg-white/10"><ChevronLeft size={19}/></button>}</div>
  {!collapsed&&<p className="-mt-5 mb-4 text-xs font-bold tracking-[.17em] text-zinc-300">HR ASSISTANT</p>}
  <button onClick={()=>onSection("assistant")} className={`group relative flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-bold transition ${section==="assistant"?"bg-[var(--sg-red)] text-white":"bg-white/10 text-white hover:bg-white/15"}`}><Plus size={19}/>{!collapsed&&<span>New chat</span>}{collapsed&&<span className="pointer-events-none absolute left-14 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">New chat</span>}</button>
  {!collapsed&&<div className="relative mt-4"><Search className="pointer-events-none absolute left-3 top-2.5 text-zinc-500" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations" className="w-full rounded-lg border border-white/10 bg-white/5 py-2 pl-9 pr-3 text-xs text-white outline-none placeholder:text-zinc-500 focus:border-white/30"/></div>}
  <nav className="mt-4 space-y-1">{items.map(({key,label,icon:Icon})=><button key={key} onClick={()=>onSection(key)} className={`group relative flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-semibold transition ${section===key?"bg-white/12 text-white":"text-zinc-400 hover:bg-white/8 hover:text-white"}`}><Icon size={18}/>{!collapsed&&<span>{label}</span>}{collapsed&&<span className="pointer-events-none absolute left-14 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">{label}</span>}</button>)}</nav>
  {!collapsed&&<div className="mt-5"><button onClick={()=>setRecentOpen(v=>!v)} aria-expanded={recentOpen} className="flex w-full items-center justify-between px-2 py-2 text-xs font-bold uppercase tracking-[.14em] text-zinc-500 hover:text-zinc-300"><span>Recent</span><ChevronDown size={15} className={recentOpen?"":"-rotate-90"}/></button>{recentOpen&&<div className="mt-1 space-y-1">{recents.length?recents.map(r=><button key={r.title} onClick={()=>onSection("assistant")} className="flex w-full items-start gap-2 rounded-lg px-2 py-2 text-left hover:bg-white/8"><MessageSquare className="mt-0.5 shrink-0 text-zinc-500" size={15}/><span className="min-w-0"><span className="block truncate text-xs font-medium text-zinc-300">{r.title}</span><span className="mt-0.5 block text-[11px] text-zinc-500">{r.when}</span></span></button>):<p className="px-2 py-2 text-xs text-zinc-500">No matching conversations</p>}</div>}</div>}
  <div className="relative mt-auto border-t border-white/15 pt-4"><button onClick={onMenu} aria-expanded={menuOpen} className="group flex w-full min-w-[42px] items-center gap-3 rounded-lg p-1 text-left hover:bg-white/10"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-zinc-600 text-xs font-bold">{persona.initials}</span>{!collapsed&&<div className="min-w-0"><p className="truncate text-sm font-semibold">{persona.name}</p><p className="truncate text-xs text-zinc-400">{persona.role}</p></div>}{collapsed&&<span className="pointer-events-none absolute bottom-10 left-14 z-50 hidden whitespace-nowrap rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow group-hover:block">{persona.name} · Settings</span>}</button>{menuOpen&&<div className={`absolute bottom-14 z-[70] w-[280px] rounded-xl border border-zinc-700 bg-zinc-900 p-2 shadow-2xl ${collapsed?"left-0":"left-0"}`}><div className="flex items-center gap-2 px-3 py-2 text-xs font-bold uppercase tracking-wider text-zinc-400"><Settings2 size={14}/> Switch demo persona</div>{personas.map(p=><button key={p.id} onClick={()=>onPersona(p.id)} className="flex w-full items-center gap-3 rounded-lg p-3 text-left hover:bg-white/10"><span className="grid h-8 w-8 place-items-center rounded-full bg-zinc-700 text-xs font-bold">{p.initials}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{p.name}</span><span className="block truncate text-xs text-zinc-400">{p.role}</span></span>{p.id===persona.id&&<Check size={16} className="text-emerald-400"/>}</button>)}</div>}</div>
</aside> }
