"use client";
import { ArrowRight, CalendarDays, Check, CheckCircle2, CircleAlert, ClipboardCheck, FileCheck2, MapPin, Send, ShieldCheck, Users } from "lucide-react";
import { scenario } from "../data/scenario";
import { PromptComposer } from "./PromptComposer";
import { type NavKey, type Persona } from "../data/personas";

export type Stage = 1|2|3|4|5|6|7|8|9|10|11|12|13;
type Props={stage:Stage;setStage:(stage:Stage)=>void;section:NavKey;persona:Persona;switchPersona:(id:Persona["id"])=>void};
const Panel=({children}:{children:React.ReactNode})=><section className="rounded-2xl border border-[var(--line)] bg-white p-5 shadow-[0_8px_28px_rgba(20,20,20,.035)]">{children}</section>;
const Badge=({children,tone="neutral"}:{children:React.ReactNode;tone?:"good"|"warn"|"red"|"neutral"})=><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${tone==="good"?"bg-emerald-50 text-emerald-700":tone==="warn"?"bg-amber-50 text-amber-800":tone==="red"?"bg-red-50 text-red-700":"bg-zinc-100 text-zinc-600"}`}>{children}</span>;
const Evidence=({items=scenario.checks}:{items?:string[]})=><div className="mt-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">Evidence checked</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{items.map(item=><div key={item} className="flex items-center gap-2 rounded-lg bg-zinc-50 px-3 py-2 text-sm"><ShieldCheck size={15} className="shrink-0 text-emerald-600"/>{item}</div>)}</div></div>;
function Header({label,title,status}:{label:string;title:string;status:string}){return <header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--sg-red)]">{label} · {scenario.id}</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight md:text-4xl">{title}</h1><Badge>{status}</Badge></div></header>}
function Action({children,onClick,primary=false}:{children:React.ReactNode;onClick:()=>void;primary?:boolean}){return <button onClick={onClick} className={`mt-6 inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-bold text-white ${primary?"bg-[var(--sg-red)]":"bg-zinc-900"}`}>{children}<ArrowRight size={16}/></button>}
export function Workbench({stage,setStage,section,persona,switchPersona}:Props){
  const go=(s:Stage)=>()=>setStage(s);
  const shell=(content:React.ReactNode)=><div className="mx-auto max-w-5xl pb-32">{content}<div className="fixed bottom-4 left-4 right-4 z-30 mx-auto max-w-3xl md:bottom-6 md:left-[calc(50%_-_350px)] md:right-auto md:w-[700px]"><PromptComposer onSend={()=>setStage(Math.min(13,stage+1) as Stage)} placeholder="Continue this connected case…"/></div></div>;
  if(section==="reports") return shell(<><Header label={`${persona.name} · reports`} title="Operational health" status="Supporting view"/><Panel><h2 className="text-2xl font-bold">Reports support the conversation; they do not replace it.</h2><p className="mt-2 text-sm text-zinc-600">Use the connected case in Assistant, Operations and Controls to make decisions. This prototype keeps reporting as a lightweight supporting destination.</p></Panel></>);
  if(section==="learning") return shell(<><Header label="Claire · team learning" title="Team learning" status="Supporting view"/><Panel><h2 className="text-2xl font-bold">View team learning context.</h2><p className="mt-2 text-sm text-zinc-600">Claire’s connected training request remains in Assistant and its completed status is in My requests.</p></Panel></>);
  if(section==="help") return shell(<><Header label="Claire · help" title="How this case works" status="Guidance"/><Panel><h2 className="text-2xl font-bold">Each person sees the decision they own.</h2><p className="mt-2 text-sm text-zinc-600">Claire requests and resolves business trade-offs; Amélie approves planning; Radu approves registrations and invitations; Elena approves control remediation.</p></Panel></>);
  if(stage===1) return shell(<div className="mx-auto max-w-3xl pt-16 md:pt-24"><h1 className="text-center text-4xl font-bold tracking-tight md:text-5xl">What does your team need to learn?</h1><div className="mt-8"><PromptComposer onSend={go(2)} placeholder="I have 12 new managers in Paris. They need New Manager Foundations before 30 September. Prefer classroom and Victor Laurent."/></div><Panel><p className="font-bold">Claire’s request</p><p className="mt-2 text-sm text-zinc-600">12 new managers · Paris classroom · before 30 September · Victor Laurent preferred.</p><Action onClick={go(2)} primary>Submit demand for planning</Action></Panel></div>);
  if(stage===2) return shell(<><Header label="Amelie · planning" title="Validate the plan" status="Ready for review"/><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Panel><Badge tone="good">Feasible proposal</Badge><h2 className="mt-3 text-2xl font-bold">A session fits the requirement and deadline.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Fact icon={<CalendarDays/>} label="Session" value={`${scenario.mainDate} · ${scenario.time}`}/><Fact icon={<MapPin/>} label="Venue" value={`${scenario.location} · 16 seats`}/><Fact icon={<Users/>} label="Trainer" value={scenario.trainer}/><Fact icon={<ClipboardCheck/>} label="Scope" value="New Manager Foundations · 12 people"/></div><Evidence/><Action onClick={go(3)} primary>Review and approve the plan</Action></Panel><Panel><p className="font-bold">Human decision</p><p className="mt-2 text-sm text-zinc-600">Registration has not started. Amelie owns curriculum fit, trainer, room, date and publication.</p></Panel></div></>);
  if(stage===3) return shell(<><Header label="Amelie · plan approval" title="Publish the session plan" status="Approval required"/><Panel><h2 className="text-2xl font-bold">Approve session {scenario.sessionRef}?</h2><p className="mt-2 text-sm text-zinc-600">The approved plan creates a work package for Radu; it does not register anyone or send invitations.</p><Evidence items={["Curriculum and planning rules passed","16-seat room reserved","Victor Laurent confirmed","Approval record will be retained"]}/><Action onClick={go(4)} primary>Approve and publish session</Action></Panel></>);
  if(stage===4) return shell(<><Header label="Amelie · hand-off" title="Session ready for Learning Operations" status="Approved"/><Panel><p className="text-xl font-bold">{scenario.sessionRef} is published with 16 seats.</p><p className="mt-2 text-sm text-zinc-600">Radu receives the date, trainer, capacity, business context and planning evidence. No invitations have been sent.</p><Action onClick={()=>{switchPersona("radu");setStage(5)}}>Open Radu’s work package</Action></Panel></>);
  if(stage===5) return shell(<><Header label="Radu · registration check" title="Check the group" status="Draft"/><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Panel><h2 className="text-2xl font-bold">Check 12 people against the approved session.</h2><p className="mt-2 text-sm text-zinc-600">The assistant checks availability, learning history, registration rules and capacity. It will not send invitations until Radu approves.</p><Evidence/><Action onClick={go(6)}>Check the group</Action></Panel><Panel><p className="font-bold">Approved session</p><p className="mt-2 text-sm text-zinc-600">{scenario.mainDate}<br/>{scenario.location}<br/>{scenario.trainer}</p></Panel></div></>);
  if(stage===6) return shell(<><Header label="Radu · exception review" title="10 are ready; 2 need a decision" status="Needs decision"/><div className="grid gap-5 lg:grid-cols-2"><Panel><Badge tone="good">10 ready to register</Badge><p className="mt-4 text-sm text-zinc-600">Radu can hold the 10 as a draft. Claire owns the business trade-off for the exceptions.</p>{scenario.people.filter(p=>p.status==="Needs decision").map(p=><div key={p.name} className="mt-4 rounded-xl border-l-4 border-[var(--sg-red)] bg-red-50/50 p-4"><p className="font-bold">{p.name}</p><p className="mt-1 text-sm">{p.note}</p><p className="mt-2 text-sm font-semibold text-[var(--sg-red)]">Recommended: {p.alternative}</p></div>)}<Action onClick={()=>{switchPersona("claire");setStage(7)}} primary>Ask Claire for a decision</Action></Panel><Panel><p className="font-bold">What remains untouched</p><p className="mt-2 text-sm text-zinc-600">No registration or invitation is created while the two exceptions await Claire’s choice.</p><Evidence items={["10 eligibility and availability checks passed","Priya calendar conflict identified","Thomas start date confirmed","Capacity remains available"]}/></Panel></div></>);
  if(stage===7) return shell(<><Header label="Claire · business decision" title="Make the business trade-off" status="Needs decision"/><Panel><h2 className="text-2xl font-bold">Keep 11 managers on track?</h2><div className="mt-5 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-zinc-50 p-4"><p className="font-bold">Priya Shah</p><p className="mt-1 text-sm text-zinc-600">Attend the alternative on {scenario.alternativeDate}.</p></div><div className="rounded-xl bg-zinc-50 p-4"><p className="font-bold">Thomas Bernard</p><p className="mt-1 text-sm text-zinc-600">Earliest option is 9 October, after the deadline. Keep as follow-up.</p></div></div><p className="mt-5 text-sm text-zinc-600">Decision: confirm 10 people on 18 September, Priya on 22 September, and leave Thomas open for a later-session choice.</p><Action onClick={()=>{switchPersona("radu");setStage(8)}} primary>Confirm 11-person plan</Action></Panel></>);
  if(stage===8) return shell(<><Header label="Radu · final approval" title="Approve and publish" status="Approval required"/><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Panel><h2 className="text-2xl font-bold">Create 11 registrations and send 11 invitations?</h2><p className="mt-2 text-sm text-zinc-600">10 registrations are for 18 September; Priya is registered for 22 September. Thomas remains a Neocase follow-up.</p><Evidence items={["MyLearning: 11 planned registrations","Outlook: 11 planned invitations","Neocase: Thomas follow-up","Radu approval and audit record"]}/><Action onClick={go(9)} primary>Approve and publish</Action></Panel><Panel><p className="text-4xl font-bold text-emerald-700">11</p><p className="text-sm text-zinc-600">confirmed registrations after approval</p><p className="mt-5 text-2xl font-bold text-amber-700">1</p><p className="text-sm text-zinc-600">follow-up required</p></Panel></div></>);
  if(stage===9) return shell(<><Header label="Radu · operations" title="Completion and proof" status="Complete"/><div className="grid gap-4 md:grid-cols-3"><Metric n="10" label="confirmed · 18 Sep"/><Metric n="1" label="confirmed · 22 Sep"/><Metric n="1" label="follow-up required"/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><h2 className="text-xl font-bold">The promised work is complete.</h2><p className="mt-2 text-sm text-zinc-600">11 registrations confirmed and 11 invitations sent. Thomas awaits Claire’s later-session decision.</p><Evidence items={["MyLearning registration IDs retained","Outlook invitation batch retained","Rule outcomes retained","Radu approval timestamp retained"]}/></Panel><Panel><p className="font-bold">Next governance step</p><p className="mt-2 text-sm text-zinc-600">Elena’s weekly invitation control will check whether each confirmed registration has a matching current invitation.</p><Action onClick={()=>{switchPersona("elena");setStage(11)}}>Open weekly control queue</Action></Panel></div></>);
  if(stage===10) return shell(<><Header label="Claire · request status" title="My request" status="Follow-up required"/><Panel><h2 className="text-2xl font-bold">Training status is clear.</h2><p className="mt-3 text-sm text-zinc-600">10 managers are confirmed for 18 September. Priya is confirmed for 22 September. Thomas still needs a later-session choice.</p><Badge tone="warn">Thomas · follow-up required</Badge></Panel></>);
  if(stage===11) return shell(<><Header label="Elena · weekly controls" title="One invitation exception needs approval" status="Control exception"/><div className="grid gap-5 lg:grid-cols-2"><Panel><Badge tone="red">INV-04 exception</Badge><h2 className="mt-3 text-2xl font-bold">Confirmed registration, no current invitation.</h2><p className="mt-2 text-sm text-zinc-600">A participant moved from a cancelled session after the original batch. The registration is correct; only a current Outlook invitation is missing.</p><Evidence items={["Control catalogue INV-04","MyLearning registration state matched","Outlook invitation match failed","Source timestamps retained"]}/><Action onClick={go(12)} primary>Review remediation</Action></Panel><Panel><p className="font-bold">Control boundary</p><p className="mt-2 text-sm text-zinc-600">Elena approves the contained repair. The assistant does not send the replacement invitation before her approval.</p></Panel></div></>);
  if(stage===12) return shell(<><Header label="Elena · remediation" title="Approve and send one invitation" status="Approval required"/><Panel><h2 className="text-2xl font-bold">Repair the invitation mismatch?</h2><p className="mt-2 text-sm text-zinc-600">Send one current invitation, retain the decision and re-check INV-04.</p><Evidence items={["One Outlook invitation planned","INV-04 approval will be recorded","Registration remains unchanged","Re-check scheduled after delivery"]}/><Action onClick={go(13)} primary>Approve remediation</Action></Panel></>);
  return shell(<><Header label="Elena · control complete" title="Invitation delivered; control passed" status="Control passed"/><Panel><CheckCircle2 className="text-emerald-600" size={30}/><h2 className="mt-3 text-2xl font-bold">The registration and invitation now match.</h2><p className="mt-2 text-sm text-zinc-600">Detection, Elena’s decision, the single invitation, re-check and final evidence have been added to the append-only audit history.</p><Evidence items={["Invitation delivery timestamp","INV-04 re-check passed","Elena approval retained","Improvement follow-up available if recurring"]}/></Panel></>);
}
function Fact({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl bg-zinc-50 p-4"><span className="text-[var(--sg-red)]">{icon}</span><p className="mt-2 text-xs font-bold uppercase tracking-wide text-zinc-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Metric({n,label}:{n:string;label:string}){return <Panel><p className="text-4xl font-bold">{n}</p><p className="mt-1 text-sm text-zinc-600">{label}</p></Panel>}
