"use client";
import { useEffect, useState } from "react";
import { Menu, PanelRightOpen, X } from "lucide-react";
import { SideNav } from "./components/SideNav";
import { Workbench, type Stage } from "./components/Workbench";
import { RightDetails } from "./components/RightDetails";
import { getPersona, type NavKey, type PersonaId } from "./data/personas";

export default function Page(){
  const [stage,setStage]=useState<Stage>(1); const [personaId,setPersonaId]=useState<PersonaId>("claire"); const [section,setSection]=useState<NavKey>("assistant"); const [collapsed,setCollapsed]=useState(false); const [detailsOpen,setDetailsOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [mobileOpen,setMobileOpen]=useState(false); const persona=getPersona(personaId); const hasConversation=section==="assistant"&&stage>1;
  useEffect(()=>{if(hasConversation)setDetailsOpen(true);else setDetailsOpen(false)},[hasConversation]);
  const switchPersona=(id:PersonaId)=>{setPersonaId(id);setSection("assistant");setStage(id==="claire"?1:id==="amelie"?2:id==="radu"?5:11);setMenuOpen(false);setMobileOpen(false);};
  const renderNav=()=> <SideNav section={section} persona={persona} collapsed={collapsed} menuOpen={menuOpen} onToggle={()=>setCollapsed(v=>!v)} onMenu={()=>setMenuOpen(v=>!v)} onPersona={switchPersona} onSection={s=>{setSection(s);setStage(s==="operations"?9:s==="controls"?11:s==="requests"?10:persona.id==="claire"?1:persona.id==="amelie"?2:persona.id==="radu"?5:11);setMobileOpen(false);}}/>;
  return <main className="flex h-dvh min-h-0 overflow-hidden bg-[var(--canvas)]"><div className="hidden h-full min-h-0 md:block">{renderNav()}</div><div className="fixed inset-x-0 top-0 z-40 flex h-14 items-center justify-between border-b border-zinc-200 bg-white px-4 md:hidden"><button aria-label="Open navigation" onClick={()=>setMobileOpen(true)} className="rounded-lg p-2 hover:bg-zinc-100"><Menu size={20}/></button><img src="/logo_dark.svg" alt="Société Générale" className="h-6 w-auto"/>{hasConversation&&<button aria-label="Open details" onClick={()=>setDetailsOpen(true)} className="rounded-lg p-2 hover:bg-zinc-100"><PanelRightOpen size={19}/></button>}</div>{mobileOpen&&<div className="fixed inset-0 z-50 flex md:hidden"><button aria-label="Close navigation" onClick={()=>setMobileOpen(false)} className="flex-1 bg-black/40"/><div className="h-full"><button aria-label="Close navigation" onClick={()=>setMobileOpen(false)} className="absolute left-[260px] top-3 rounded bg-white p-2 text-zinc-900"><X size={17}/></button>{renderNav()}</div></div>}<div className="min-h-0 min-w-0 flex-1 overflow-y-auto overscroll-contain pt-14 md:pt-0"><div className="mx-auto min-h-full max-w-[1600px] px-5 py-6 md:px-10 md:py-8 lg:px-14">{hasConversation&&<div className="mb-3 flex justify-end"><button onClick={()=>setDetailsOpen(true)} className="hidden items-center gap-2 rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm font-bold text-zinc-700 hover:bg-zinc-50 md:inline-flex"><PanelRightOpen size={16}/> Details</button></div>}<Workbench stage={stage} setStage={setStage} section={section} persona={persona} switchPersona={switchPersona}/></div></div>{hasConversation&&<RightDetails open={detailsOpen} onClose={()=>setDetailsOpen(false)}/>}</main>
}
